/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsCreateRouteImport } from './routes/admin/events/create'
import { Route as EventsEventIdEventNameStaffPortalRouteImport } from './routes/events/$eventId/$eventName/staff-portal'
import { Route as EventsEventIdEventNameLoginRouteImport } from './routes/events/$eventId/$eventName/login'
import { Route as AdminEventsEventIdEventNameRouteImport } from './routes/admin/events/$eventId/$eventName'
import { Route as EventsEventIdEventNameStaffPortalIndexRouteImport } from './routes/events/$eventId/$eventName/staff-portal/index'
import { Route as EventsEventIdEventNameStaffPortalScanRouteImport } from './routes/events/$eventId/$eventName/staff-portal/scan'
import { Route as EventsEventIdEventNameStaffPortalParticipantsRouteImport } from './routes/events/$eventId/$eventName/staff-portal/participants'
import { Route as EventsEventIdEventNameStaffPortalAttendanceRouteImport } from './routes/events/$eventId/$eventName/staff-portal/attendance'
import { Route as AdminEventsEventIdEventNameStaffRouteImport } from './routes/admin/events/$eventId/$eventName/staff'
import { Route as AdminEventsEventIdEventNameParticipantsRouteImport } from './routes/admin/events/$eventId/$eventName/participants'
import { Route as AdminEventsEventIdEventNameHallsRouteImport } from './routes/admin/events/$eventId/$eventName/halls'
import { Route as AdminEventsEventIdEventNameDashboardRouteImport } from './routes/admin/events/$eventId/$eventName/dashboard'
import { Route as AdminEventsEventIdEventNameCoursesRouteImport } from './routes/admin/events/$eventId/$eventName/courses'
import { Route as AdminEventsEventIdEventNameBadgeLayoutRouteImport } from './routes/admin/events/$eventId/$eventName/badge-layout'
import { Route as AdminEventsEventIdEventNameAttendanceRouteImport } from './routes/admin/events/$eventId/$eventName/attendance'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsCreateRoute = AdminEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => AdminRoute,
} as any)
const EventsEventIdEventNameStaffPortalRoute =
  EventsEventIdEventNameStaffPortalRouteImport.update({
    id: '/$eventId/$eventName/staff-portal',
    path: '/$eventId/$eventName/staff-portal',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsEventIdEventNameLoginRoute =
  EventsEventIdEventNameLoginRouteImport.update({
    id: '/$eventId/$eventName/login',
    path: '/$eventId/$eventName/login',
    getParentRoute: () => EventsRoute,
  } as any)
const AdminEventsEventIdEventNameRoute =
  AdminEventsEventIdEventNameRouteImport.update({
    id: '/events/$eventId/$eventName',
    path: '/events/$eventId/$eventName',
    getParentRoute: () => AdminRoute,
  } as any)
const EventsEventIdEventNameStaffPortalIndexRoute =
  EventsEventIdEventNameStaffPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EventsEventIdEventNameStaffPortalRoute,
  } as any)
const EventsEventIdEventNameStaffPortalScanRoute =
  EventsEventIdEventNameStaffPortalScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => EventsEventIdEventNameStaffPortalRoute,
  } as any)
const EventsEventIdEventNameStaffPortalParticipantsRoute =
  EventsEventIdEventNameStaffPortalParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => EventsEventIdEventNameStaffPortalRoute,
  } as any)
const EventsEventIdEventNameStaffPortalAttendanceRoute =
  EventsEventIdEventNameStaffPortalAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => EventsEventIdEventNameStaffPortalRoute,
  } as any)
const AdminEventsEventIdEventNameStaffRoute =
  AdminEventsEventIdEventNameStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameParticipantsRoute =
  AdminEventsEventIdEventNameParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameHallsRoute =
  AdminEventsEventIdEventNameHallsRouteImport.update({
    id: '/halls',
    path: '/halls',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameDashboardRoute =
  AdminEventsEventIdEventNameDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameCoursesRoute =
  AdminEventsEventIdEventNameCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameBadgeLayoutRoute =
  AdminEventsEventIdEventNameBadgeLayoutRouteImport.update({
    id: '/badge-layout',
    path: '/badge-layout',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)
const AdminEventsEventIdEventNameAttendanceRoute =
  AdminEventsEventIdEventNameAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AdminEventsEventIdEventNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/$eventName': typeof AdminEventsEventIdEventNameRouteWithChildren
  '/events/$eventId/$eventName/login': typeof EventsEventIdEventNameLoginRoute
  '/events/$eventId/$eventName/staff-portal': typeof EventsEventIdEventNameStaffPortalRouteWithChildren
  '/admin/events/$eventId/$eventName/attendance': typeof AdminEventsEventIdEventNameAttendanceRoute
  '/admin/events/$eventId/$eventName/badge-layout': typeof AdminEventsEventIdEventNameBadgeLayoutRoute
  '/admin/events/$eventId/$eventName/courses': typeof AdminEventsEventIdEventNameCoursesRoute
  '/admin/events/$eventId/$eventName/dashboard': typeof AdminEventsEventIdEventNameDashboardRoute
  '/admin/events/$eventId/$eventName/halls': typeof AdminEventsEventIdEventNameHallsRoute
  '/admin/events/$eventId/$eventName/participants': typeof AdminEventsEventIdEventNameParticipantsRoute
  '/admin/events/$eventId/$eventName/staff': typeof AdminEventsEventIdEventNameStaffRoute
  '/events/$eventId/$eventName/staff-portal/attendance': typeof EventsEventIdEventNameStaffPortalAttendanceRoute
  '/events/$eventId/$eventName/staff-portal/participants': typeof EventsEventIdEventNameStaffPortalParticipantsRoute
  '/events/$eventId/$eventName/staff-portal/scan': typeof EventsEventIdEventNameStaffPortalScanRoute
  '/events/$eventId/$eventName/staff-portal/': typeof EventsEventIdEventNameStaffPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/$eventName': typeof AdminEventsEventIdEventNameRouteWithChildren
  '/events/$eventId/$eventName/login': typeof EventsEventIdEventNameLoginRoute
  '/admin/events/$eventId/$eventName/attendance': typeof AdminEventsEventIdEventNameAttendanceRoute
  '/admin/events/$eventId/$eventName/badge-layout': typeof AdminEventsEventIdEventNameBadgeLayoutRoute
  '/admin/events/$eventId/$eventName/courses': typeof AdminEventsEventIdEventNameCoursesRoute
  '/admin/events/$eventId/$eventName/dashboard': typeof AdminEventsEventIdEventNameDashboardRoute
  '/admin/events/$eventId/$eventName/halls': typeof AdminEventsEventIdEventNameHallsRoute
  '/admin/events/$eventId/$eventName/participants': typeof AdminEventsEventIdEventNameParticipantsRoute
  '/admin/events/$eventId/$eventName/staff': typeof AdminEventsEventIdEventNameStaffRoute
  '/events/$eventId/$eventName/staff-portal/attendance': typeof EventsEventIdEventNameStaffPortalAttendanceRoute
  '/events/$eventId/$eventName/staff-portal/participants': typeof EventsEventIdEventNameStaffPortalParticipantsRoute
  '/events/$eventId/$eventName/staff-portal/scan': typeof EventsEventIdEventNameStaffPortalScanRoute
  '/events/$eventId/$eventName/staff-portal': typeof EventsEventIdEventNameStaffPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/$eventName': typeof AdminEventsEventIdEventNameRouteWithChildren
  '/events/$eventId/$eventName/login': typeof EventsEventIdEventNameLoginRoute
  '/events/$eventId/$eventName/staff-portal': typeof EventsEventIdEventNameStaffPortalRouteWithChildren
  '/admin/events/$eventId/$eventName/attendance': typeof AdminEventsEventIdEventNameAttendanceRoute
  '/admin/events/$eventId/$eventName/badge-layout': typeof AdminEventsEventIdEventNameBadgeLayoutRoute
  '/admin/events/$eventId/$eventName/courses': typeof AdminEventsEventIdEventNameCoursesRoute
  '/admin/events/$eventId/$eventName/dashboard': typeof AdminEventsEventIdEventNameDashboardRoute
  '/admin/events/$eventId/$eventName/halls': typeof AdminEventsEventIdEventNameHallsRoute
  '/admin/events/$eventId/$eventName/participants': typeof AdminEventsEventIdEventNameParticipantsRoute
  '/admin/events/$eventId/$eventName/staff': typeof AdminEventsEventIdEventNameStaffRoute
  '/events/$eventId/$eventName/staff-portal/attendance': typeof EventsEventIdEventNameStaffPortalAttendanceRoute
  '/events/$eventId/$eventName/staff-portal/participants': typeof EventsEventIdEventNameStaffPortalParticipantsRoute
  '/events/$eventId/$eventName/staff-portal/scan': typeof EventsEventIdEventNameStaffPortalScanRoute
  '/events/$eventId/$eventName/staff-portal/': typeof EventsEventIdEventNameStaffPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/login'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/events/create'
    | '/admin/events'
    | '/admin/events/$eventId/$eventName'
    | '/events/$eventId/$eventName/login'
    | '/events/$eventId/$eventName/staff-portal'
    | '/admin/events/$eventId/$eventName/attendance'
    | '/admin/events/$eventId/$eventName/badge-layout'
    | '/admin/events/$eventId/$eventName/courses'
    | '/admin/events/$eventId/$eventName/dashboard'
    | '/admin/events/$eventId/$eventName/halls'
    | '/admin/events/$eventId/$eventName/participants'
    | '/admin/events/$eventId/$eventName/staff'
    | '/events/$eventId/$eventName/staff-portal/attendance'
    | '/events/$eventId/$eventName/staff-portal/participants'
    | '/events/$eventId/$eventName/staff-portal/scan'
    | '/events/$eventId/$eventName/staff-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/login'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/events/create'
    | '/admin/events'
    | '/admin/events/$eventId/$eventName'
    | '/events/$eventId/$eventName/login'
    | '/admin/events/$eventId/$eventName/attendance'
    | '/admin/events/$eventId/$eventName/badge-layout'
    | '/admin/events/$eventId/$eventName/courses'
    | '/admin/events/$eventId/$eventName/dashboard'
    | '/admin/events/$eventId/$eventName/halls'
    | '/admin/events/$eventId/$eventName/participants'
    | '/admin/events/$eventId/$eventName/staff'
    | '/events/$eventId/$eventName/staff-portal/attendance'
    | '/events/$eventId/$eventName/staff-portal/participants'
    | '/events/$eventId/$eventName/staff-portal/scan'
    | '/events/$eventId/$eventName/staff-portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/login'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/events/create'
    | '/admin/events/'
    | '/admin/events/$eventId/$eventName'
    | '/events/$eventId/$eventName/login'
    | '/events/$eventId/$eventName/staff-portal'
    | '/admin/events/$eventId/$eventName/attendance'
    | '/admin/events/$eventId/$eventName/badge-layout'
    | '/admin/events/$eventId/$eventName/courses'
    | '/admin/events/$eventId/$eventName/dashboard'
    | '/admin/events/$eventId/$eventName/halls'
    | '/admin/events/$eventId/$eventName/participants'
    | '/admin/events/$eventId/$eventName/staff'
    | '/events/$eventId/$eventName/staff-portal/attendance'
    | '/events/$eventId/$eventName/staff-portal/participants'
    | '/events/$eventId/$eventName/staff-portal/scan'
    | '/events/$eventId/$eventName/staff-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/create': {
      id: '/admin/events/create'
      path: '/events/create'
      fullPath: '/admin/events/create'
      preLoaderRoute: typeof AdminEventsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId/$eventName/staff-portal': {
      id: '/events/$eventId/$eventName/staff-portal'
      path: '/$eventId/$eventName/staff-portal'
      fullPath: '/events/$eventId/$eventName/staff-portal'
      preLoaderRoute: typeof EventsEventIdEventNameStaffPortalRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId/$eventName/login': {
      id: '/events/$eventId/$eventName/login'
      path: '/$eventId/$eventName/login'
      fullPath: '/events/$eventId/$eventName/login'
      preLoaderRoute: typeof EventsEventIdEventNameLoginRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/events/$eventId/$eventName': {
      id: '/admin/events/$eventId/$eventName'
      path: '/events/$eventId/$eventName'
      fullPath: '/admin/events/$eventId/$eventName'
      preLoaderRoute: typeof AdminEventsEventIdEventNameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId/$eventName/staff-portal/': {
      id: '/events/$eventId/$eventName/staff-portal/'
      path: '/'
      fullPath: '/events/$eventId/$eventName/staff-portal/'
      preLoaderRoute: typeof EventsEventIdEventNameStaffPortalIndexRouteImport
      parentRoute: typeof EventsEventIdEventNameStaffPortalRoute
    }
    '/events/$eventId/$eventName/staff-portal/scan': {
      id: '/events/$eventId/$eventName/staff-portal/scan'
      path: '/scan'
      fullPath: '/events/$eventId/$eventName/staff-portal/scan'
      preLoaderRoute: typeof EventsEventIdEventNameStaffPortalScanRouteImport
      parentRoute: typeof EventsEventIdEventNameStaffPortalRoute
    }
    '/events/$eventId/$eventName/staff-portal/participants': {
      id: '/events/$eventId/$eventName/staff-portal/participants'
      path: '/participants'
      fullPath: '/events/$eventId/$eventName/staff-portal/participants'
      preLoaderRoute: typeof EventsEventIdEventNameStaffPortalParticipantsRouteImport
      parentRoute: typeof EventsEventIdEventNameStaffPortalRoute
    }
    '/events/$eventId/$eventName/staff-portal/attendance': {
      id: '/events/$eventId/$eventName/staff-portal/attendance'
      path: '/attendance'
      fullPath: '/events/$eventId/$eventName/staff-portal/attendance'
      preLoaderRoute: typeof EventsEventIdEventNameStaffPortalAttendanceRouteImport
      parentRoute: typeof EventsEventIdEventNameStaffPortalRoute
    }
    '/admin/events/$eventId/$eventName/staff': {
      id: '/admin/events/$eventId/$eventName/staff'
      path: '/staff'
      fullPath: '/admin/events/$eventId/$eventName/staff'
      preLoaderRoute: typeof AdminEventsEventIdEventNameStaffRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/participants': {
      id: '/admin/events/$eventId/$eventName/participants'
      path: '/participants'
      fullPath: '/admin/events/$eventId/$eventName/participants'
      preLoaderRoute: typeof AdminEventsEventIdEventNameParticipantsRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/halls': {
      id: '/admin/events/$eventId/$eventName/halls'
      path: '/halls'
      fullPath: '/admin/events/$eventId/$eventName/halls'
      preLoaderRoute: typeof AdminEventsEventIdEventNameHallsRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/dashboard': {
      id: '/admin/events/$eventId/$eventName/dashboard'
      path: '/dashboard'
      fullPath: '/admin/events/$eventId/$eventName/dashboard'
      preLoaderRoute: typeof AdminEventsEventIdEventNameDashboardRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/courses': {
      id: '/admin/events/$eventId/$eventName/courses'
      path: '/courses'
      fullPath: '/admin/events/$eventId/$eventName/courses'
      preLoaderRoute: typeof AdminEventsEventIdEventNameCoursesRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/badge-layout': {
      id: '/admin/events/$eventId/$eventName/badge-layout'
      path: '/badge-layout'
      fullPath: '/admin/events/$eventId/$eventName/badge-layout'
      preLoaderRoute: typeof AdminEventsEventIdEventNameBadgeLayoutRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
    '/admin/events/$eventId/$eventName/attendance': {
      id: '/admin/events/$eventId/$eventName/attendance'
      path: '/attendance'
      fullPath: '/admin/events/$eventId/$eventName/attendance'
      preLoaderRoute: typeof AdminEventsEventIdEventNameAttendanceRouteImport
      parentRoute: typeof AdminEventsEventIdEventNameRoute
    }
  }
}

interface AdminEventsEventIdEventNameRouteChildren {
  AdminEventsEventIdEventNameAttendanceRoute: typeof AdminEventsEventIdEventNameAttendanceRoute
  AdminEventsEventIdEventNameBadgeLayoutRoute: typeof AdminEventsEventIdEventNameBadgeLayoutRoute
  AdminEventsEventIdEventNameCoursesRoute: typeof AdminEventsEventIdEventNameCoursesRoute
  AdminEventsEventIdEventNameDashboardRoute: typeof AdminEventsEventIdEventNameDashboardRoute
  AdminEventsEventIdEventNameHallsRoute: typeof AdminEventsEventIdEventNameHallsRoute
  AdminEventsEventIdEventNameParticipantsRoute: typeof AdminEventsEventIdEventNameParticipantsRoute
  AdminEventsEventIdEventNameStaffRoute: typeof AdminEventsEventIdEventNameStaffRoute
}

const AdminEventsEventIdEventNameRouteChildren: AdminEventsEventIdEventNameRouteChildren =
  {
    AdminEventsEventIdEventNameAttendanceRoute:
      AdminEventsEventIdEventNameAttendanceRoute,
    AdminEventsEventIdEventNameBadgeLayoutRoute:
      AdminEventsEventIdEventNameBadgeLayoutRoute,
    AdminEventsEventIdEventNameCoursesRoute:
      AdminEventsEventIdEventNameCoursesRoute,
    AdminEventsEventIdEventNameDashboardRoute:
      AdminEventsEventIdEventNameDashboardRoute,
    AdminEventsEventIdEventNameHallsRoute:
      AdminEventsEventIdEventNameHallsRoute,
    AdminEventsEventIdEventNameParticipantsRoute:
      AdminEventsEventIdEventNameParticipantsRoute,
    AdminEventsEventIdEventNameStaffRoute:
      AdminEventsEventIdEventNameStaffRoute,
  }

const AdminEventsEventIdEventNameRouteWithChildren =
  AdminEventsEventIdEventNameRoute._addFileChildren(
    AdminEventsEventIdEventNameRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsCreateRoute: typeof AdminEventsCreateRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEventIdEventNameRoute: typeof AdminEventsEventIdEventNameRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsCreateRoute: AdminEventsCreateRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEventIdEventNameRoute:
    AdminEventsEventIdEventNameRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsEventIdEventNameStaffPortalRouteChildren {
  EventsEventIdEventNameStaffPortalAttendanceRoute: typeof EventsEventIdEventNameStaffPortalAttendanceRoute
  EventsEventIdEventNameStaffPortalParticipantsRoute: typeof EventsEventIdEventNameStaffPortalParticipantsRoute
  EventsEventIdEventNameStaffPortalScanRoute: typeof EventsEventIdEventNameStaffPortalScanRoute
  EventsEventIdEventNameStaffPortalIndexRoute: typeof EventsEventIdEventNameStaffPortalIndexRoute
}

const EventsEventIdEventNameStaffPortalRouteChildren: EventsEventIdEventNameStaffPortalRouteChildren =
  {
    EventsEventIdEventNameStaffPortalAttendanceRoute:
      EventsEventIdEventNameStaffPortalAttendanceRoute,
    EventsEventIdEventNameStaffPortalParticipantsRoute:
      EventsEventIdEventNameStaffPortalParticipantsRoute,
    EventsEventIdEventNameStaffPortalScanRoute:
      EventsEventIdEventNameStaffPortalScanRoute,
    EventsEventIdEventNameStaffPortalIndexRoute:
      EventsEventIdEventNameStaffPortalIndexRoute,
  }

const EventsEventIdEventNameStaffPortalRouteWithChildren =
  EventsEventIdEventNameStaffPortalRoute._addFileChildren(
    EventsEventIdEventNameStaffPortalRouteChildren,
  )

interface EventsRouteChildren {
  EventsEventIdEventNameLoginRoute: typeof EventsEventIdEventNameLoginRoute
  EventsEventIdEventNameStaffPortalRoute: typeof EventsEventIdEventNameStaffPortalRouteWithChildren
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdEventNameLoginRoute: EventsEventIdEventNameLoginRoute,
  EventsEventIdEventNameStaffPortalRoute:
    EventsEventIdEventNameStaffPortalRouteWithChildren,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
